apiVersion: v1
kind: Secret
metadata:
  name: kleidart-frontend-secrets
type: Opaque
stringData:
  # Frontend 
  VITE_RAZORPAY_KEY_ID: "{{ .Values.FRONTEND.SECRETS.VITE_RAZORPAY_KEY_ID }}"
  VITE_RAZORPAY_KEY_SECRET: "{{ .Values.FRONTEND.SECRETS.VITE_RAZORPAY_KEY_SECRET }}"
  VITE_JWT_SECRET: "{{ .Values.FRONTEND.SECRETS.VITE_JWT_SECRET }}"
  VITE_API_BASE_URL: "{{ .Values.FRONTEND.SECRETS.VITE_API_BASE_URL}}"
...

apiVersion: v1
kind: Secret
metadata:
  name: kleidart-backend-secrets
type: Opaque
stringData:
  # Backend
  RAZORPAY_KEY_ID: "{{ .Values.BACKEND.SECRETS.RAZORPAY_KEY_ID }}"
  RAZORPAY_KEY_SECRET: "{{ .Values.BACKEND.SECRETS.RAZORPAY_KEY_SECRET }}"

  MONGO_URI: "{{ .Values.BACKEND.SECRETS.MONGO_URI }}"

  EMAIL_USER: "{{ .Values.BACKEND.SECRETS.EMAIL_USER }}"
  EMAIL_PASS: "{{ .Values.BACKEND.SECRETS.EMAIL_PASS }}"

  ALLOW_ORIGIN: "{{ .Values.BACKEND.SECRETS.ALLOW_ORIGIN }}"
  BASE_URL: "{{ .Values.BACKEND.SECRETS.BASE_URL }}"

  JWT_SECRET: "{{ .Values.BACKEND.SECRETS.JWT_SECRET }}"
  CLOUDINARY_API_SECRET: "{{ .Values.BACKEND.SECRETS.CLOUDINARY_API_SECRET }}"
  CLOUDINARY_API_KEY: "{{ .Values.BACKEND.SECRETS.CLOUDINARY_API_KEY }}"
  CLOUDINARY_CLOUDNAME: "{{ .Values.BACKEND.SECRETS.CLOUDINARY_CLOUDNAME }}"

  PORT: "{{ .Values.BACKEND.SECRETS.PORT }}"
